name: rebuild
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Solicita Rebuild
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{secrets.PROD_DIR}}
            ${{secrets.PROD_DIR}}/construye.sh ${{secrets.PROD_DIR}}
            exit 0
          host: ${{ secrets.PROD_HOST }}
          user: ${{secrets.PROD_USER}}
          key: ${{ secrets.PROD_PASS}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"  
