name: test
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Solicita Rebuild
        uses: fifsky/ssh-action@master
        with:
          command: |
            touch ~/acinco-web-prod
            exit 0
          host: ${{ secrets.PROD_HOST }}
          user: notenableduser
          key: ${{ secrets.PROD_PASS}}
#          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"  
