name: Production Continue Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Remote - Test Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          username: ${{ secrets.ACINCO_PROD_SSH_USER }}
          key: ${{ secrets.ACINCO_PROD_SSH_KEY }}
          script: |
            ls

      - name: Install Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Packages
        run: npm install

      - name: Set Environment
        run: |
          mv .env.production .env
          rm -rf .env.*

      - name: Build
        run: npm run build

      - name: Remote - Clean Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          username: ${{ secrets.ACINCO_PROD_SSH_USER }}
          key: ${{ secrets.ACINCO_PROD_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web
            mkdir -p /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/build
            rm -rf /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/*

      - name: Remote - Copy Build Files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: build/
          remote_path: /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/build/
          remote_host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          remote_user: ${{ secrets.ACINCO_PROD_SSH_USER }}
          remote_key: ${{ secrets.ACINCO_PROD_SSH_KEY }}

      - name: Remote - Copy Deployment Files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: deployment/
          remote_path: /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/
          remote_host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          remote_user: ${{ secrets.ACINCO_PROD_SSH_USER }}
          remote_key: ${{ secrets.ACINCO_PROD_SSH_KEY }}

      - name: Remote - Build Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          username: ${{ secrets.ACINCO_PROD_SSH_USER }}
          key: ${{ secrets.ACINCO_PROD_SSH_KEY }}
          script: |
            cd /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/
            docker build -t eceleris/acinco-web .

      - name: Remote - Deploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_PROD_SSH_HOST }}
          username: ${{ secrets.ACINCO_PROD_SSH_USER }}
          key: ${{ secrets.ACINCO_PROD_SSH_KEY }}
          script: |
            cd /home/${{ secrets.ACINCO_PROD_SSH_USER }}/acinco-web/
            docker stop acinco-web
            docker rm acinco-web
            docker run -d --name=acinco-web -p 127.0.0.1:8080:80 eceleris/acinco-web
