name: Cleanup Old actions workflows
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
