name: Stage Continue Deployment
on:
  push:
    branches:
      - stage
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Remote - Test Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_STAGE_SSH_HOST }}
          username: ${{ secrets.ACINCO_STAGE_SSH_USER }}
          key: ${{ secrets.ACINCO_STAGE_SSH_KEY }}
          script: |
            cd ${{secrets.QA_DIR}}
            git checkout stage
            git pull origin stage

      - name: Remote - Test Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_STAGE_SSH_HOST }}
          username: ${{ secrets.ACINCO_STAGE_SSH_USER }}
          key: ${{ secrets.ACINCO_STAGE_SSH_KEY }}
          script: |
            cd ${{secrets.QA_DIR}}
            echo "Ejecutando 'npm install'"
            npm install
            
      - name: Remote - Clean Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_STAGE_SSH_HOST }}
          username: ${{ secrets.ACINCO_STAGE_SSH_USER }}
          key: ${{ secrets.ACINCO_STAGE_SSH_KEY }}
          script: |
            cd ${{secrets.QA_DIR}}
            echo "Ejecutando 'npm run build'"
            /usr/bin/npm run build

      - name: Remote - Build Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ACINCO_STAGE_SSH_HOST }}
          username: ${{ secrets.ACINCO_STAGE_SSH_USER }}
          key: ${{ secrets.ACINCO_STAGE_SSH_KEY }}
          script: |
            cd ${{secrets.QA_DIR}}
            echo "Reiniciando servidor nginx (reload)"
            sudo /usr/sbin/service nginx reload
